export const FEATURES_LIST = [
  'Bluetooth',
  'Sat Nav',
  'Leather Seats',
  'Heated Seats',
  'Cruise Control',
  'Parking Sensors',
  'Reversing Camera',
  'Apple CarPlay',
  'Android Auto',
  'Climate Control',
  'Panoramic Roof',
  'Alloy Wheels',
  'Keyless Entry',
  'Push Button Start',
  'DAB Radio',
  'USB Port',
  'Lane Assist',
  'Blind Spot Monitoring',
  'Adaptive Headlights',
  'Rain Sensing Wipers',
  'Electric Mirrors',
  'Electric Windows',
  'ISOFIX Points',
  'Split Rear Seats',
  'Roof Rails',
  'Towing Hook',
  'Sport Mode',
  'Ambient Lighting',
  'Wireless Charging',
  'Head-Up Display',
  '360 Camera',
  'Power Tailgate',
  'Memory Seats',
  'Ventilated Seats',
  'Heated Steering Wheel',
  'Auto-Dimming Mirrors',
  'Traffic Sign Recognition',
  'Adaptive Cruise Control',
  'Auto Parking',
  'Start/Stop System',
] as const

export const BODY_TYPES = ['Saloon', 'Sedan', 'Coupe', 'Estate', 'SUV', 'Hatchback', 'Convertible', 'Pickup'] as const
export const FUEL_TYPES = ['Petrol', 'Diesel', 'Hybrid', 'Electric', 'Plug-in Hybrid'] as const
export const TRANSMISSIONS = ['Manual', 'Automatic', 'Semi-Auto', 'PDK', 'CVT'] as const
export const STATUSES = ['Available', 'Reserved', 'Sold', 'Coming Soon', 'In Preparation'] as const
